
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 20 15:34:17 GMT 2023
//----------------------------------------------------

package compiler.syntax;

import java_cup.runtime.Symbol;
import java.util.*;
import es.uned.lsi.compiler.lexical.*;
import es.uned.lsi.compiler.code.*;
import es.uned.lsi.compiler.intermediate.*;
import es.uned.lsi.compiler.semantic.*;
import es.uned.lsi.compiler.semantic.symbol.*;
import es.uned.lsi.compiler.semantic.type.*;
import es.uned.lsi.compiler.syntax.*;
import compiler.CompilerContext;
import compiler.lexical.*;
import compiler.syntax.nonTerminal.*;
import compiler.semantic.symbol.*;
import compiler.semantic.type.*;
import compiler.intermediate.*;
import compiler.code.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon Feb 20 15:34:17 GMT 2023
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\134\000\002\002\004\000\002\053\002\000\002\002" +
    "\004\000\002\054\002\000\002\003\004\000\002\004\006" +
    "\000\002\004\005\000\002\014\004\000\002\014\003\000" +
    "\002\006\002\000\002\015\006\000\002\016\004\000\002" +
    "\016\003\000\002\017\011\000\002\020\003\000\002\020" +
    "\003\000\002\021\004\000\002\021\003\000\002\022\005" +
    "\000\002\022\005\000\002\023\005\000\002\023\003\000" +
    "\002\024\003\000\002\024\005\000\002\007\004\000\002" +
    "\007\003\000\002\010\013\000\002\010\013\000\002\010" +
    "\014\000\002\010\014\000\002\011\003\000\002\011\003" +
    "\000\002\012\003\000\002\012\005\000\002\013\004\000" +
    "\002\013\004\000\002\005\012\000\002\005\013\000\002" +
    "\025\003\000\002\025\003\000\002\025\005\000\002\025" +
    "\005\000\002\025\005\000\002\025\004\000\002\025\004" +
    "\000\002\025\005\000\002\025\005\000\002\025\005\000" +
    "\002\025\003\000\002\025\003\000\002\026\006\000\002" +
    "\027\006\000\002\027\005\000\002\046\003\000\002\046" +
    "\005\000\002\030\006\000\002\030\005\000\002\031\004" +
    "\000\002\031\003\000\002\032\003\000\002\032\003\000" +
    "\002\032\003\000\002\032\003\000\002\032\003\000\002" +
    "\032\003\000\002\032\003\000\002\032\003\000\002\032" +
    "\003\000\002\032\003\000\002\052\004\000\002\052\005" +
    "\000\002\033\005\000\002\034\006\000\002\035\003\000" +
    "\002\035\003\000\002\036\006\000\002\037\011\000\002" +
    "\037\007\000\002\040\012\000\002\041\004\000\002\041" +
    "\003\000\002\042\010\000\002\043\007\000\002\043\003" +
    "\000\002\044\007\000\002\045\004\000\002\047\007\000" +
    "\002\047\007\000\002\050\003\000\002\050\003\000\002" +
    "\051\003\000\002\051\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\317\000\014\027\000\031\000\043\000\044\000\045" +
    "\000\001\002\000\004\002\321\001\002\000\014\027\ufffe" +
    "\031\ufffe\043\ufffe\044\ufffe\045\ufffe\001\002\000\004\002" +
    "\uffff\001\002\000\014\027\011\031\ufff8\043\ufff8\044\ufff8" +
    "\045\ufff8\001\002\000\004\002\ufffd\001\002\000\004\045" +
    "\316\001\002\000\014\027\011\031\ufff8\043\ufff8\044\ufff8" +
    "\045\ufff8\001\002\000\012\031\ufff8\043\017\044\ufff8\045" +
    "\ufff8\001\002\000\012\031\ufff9\043\ufff9\044\ufff9\045\ufff9" +
    "\001\002\000\010\031\041\044\040\045\033\001\002\000" +
    "\030\012\ufff8\031\ufff8\032\ufff8\033\ufff8\034\ufff8\035\ufff8" +
    "\040\ufff8\041\ufff8\043\017\044\ufff8\045\ufff8\001\002\000" +
    "\004\031\021\001\002\000\026\012\ufff5\031\ufff5\032\ufff5" +
    "\033\ufff5\034\ufff5\035\ufff5\040\ufff5\041\ufff5\044\ufff5\045" +
    "\ufff5\001\002\000\004\045\022\001\002\000\004\010\023" +
    "\001\002\000\006\045\025\046\024\001\002\000\004\011" +
    "\ufff3\001\002\000\004\011\ufff2\001\002\000\004\011\027" +
    "\001\002\000\004\016\030\001\002\000\030\012\ufff4\031" +
    "\ufff4\032\ufff4\033\ufff4\034\ufff4\035\ufff4\040\ufff4\041\ufff4" +
    "\043\ufff4\044\ufff4\045\ufff4\001\002\000\026\012\ufff6\031" +
    "\ufff6\032\ufff6\033\ufff6\034\ufff6\035\ufff6\040\ufff6\041\ufff6" +
    "\044\ufff6\045\ufff6\001\002\000\026\012\ufff0\031\ufff0\032" +
    "\ufff0\033\ufff0\034\ufff0\035\ufff0\040\ufff0\041\ufff0\044\ufff0" +
    "\045\ufff0\001\002\000\004\045\047\001\002\000\004\002" +
    "\uffe8\001\002\000\006\031\313\044\040\001\002\000\004" +
    "\002\ufffb\001\002\000\010\031\041\044\040\045\033\001" +
    "\002\000\006\037\265\045\264\001\002\000\004\045\043" +
    "\001\002\000\004\016\263\001\002\000\012\014\052\016" +
    "\uffeb\017\uffeb\024\050\001\002\000\006\016\uffec\017\045" +
    "\001\002\000\004\045\047\001\002\000\004\016\uffed\001" +
    "\002\000\010\016\uffeb\017\uffeb\024\050\001\002\000\004" +
    "\046\051\001\002\000\006\016\uffea\017\uffea\001\002\000" +
    "\010\015\ufff8\031\060\045\053\001\002\000\004\045\262" +
    "\001\002\000\006\015\uffe1\017\260\001\002\000\004\015" +
    "\062\001\002\000\004\015\uffe3\001\002\000\004\015\uffe2" +
    "\001\002\000\004\045\061\001\002\000\006\015\uffdf\017" +
    "\uffdf\001\002\000\004\012\063\001\002\000\026\012\ufff8" +
    "\031\ufff8\032\ufff8\033\ufff8\034\ufff8\035\ufff8\040\ufff8\041" +
    "\ufff8\043\017\045\ufff8\001\002\000\024\012\065\031\111" +
    "\032\102\033\104\034\073\035\112\040\070\041\105\045" +
    "\107\001\002\000\024\012\065\031\111\032\102\033\104" +
    "\034\073\035\112\040\070\041\105\045\107\001\002\000" +
    "\026\012\uffc1\013\uffc1\032\uffc1\033\uffc1\034\uffc1\035\uffc1" +
    "\040\uffc1\041\uffc1\042\uffc1\045\uffc1\001\002\000\026\012" +
    "\uffc2\013\uffc2\032\uffc2\033\uffc2\034\uffc2\035\uffc2\040\uffc2" +
    "\041\uffc2\042\uffc2\045\uffc2\001\002\000\014\014\125\016" +
    "\250\021\134\045\135\046\130\001\002\000\024\012\065" +
    "\031\111\032\102\033\104\034\073\035\112\040\070\041" +
    "\105\045\107\001\002\000\006\023\uffb7\024\uffb7\001\002" +
    "\000\004\014\220\001\002\000\026\012\uffc4\013\uffc4\032" +
    "\uffc4\033\uffc4\034\uffc4\035\uffc4\040\uffc4\041\uffc4\042\uffc4" +
    "\045\uffc4\001\002\000\004\016\217\001\002\000\006\023" +
    "\211\024\212\001\002\000\026\012\uffbd\013\uffbd\032\uffbd" +
    "\033\uffbd\034\uffbd\035\uffbd\040\uffbd\041\uffbd\042\uffbd\045" +
    "\uffbd\001\002\000\026\012\uffc5\013\uffc5\032\uffc5\033\uffc5" +
    "\034\uffc5\035\uffc5\040\uffc5\041\uffc5\042\uffc5\045\uffc5\001" +
    "\002\000\024\012\uffc7\013\uffc7\032\uffc7\033\uffc7\034\uffc7" +
    "\035\uffc7\040\uffc7\041\uffc7\045\uffc7\001\002\000\004\014" +
    "\203\001\002\000\026\012\uffbe\013\uffbe\032\uffbe\033\uffbe" +
    "\034\uffbe\035\uffbe\040\uffbe\041\uffbe\042\uffbe\045\uffbe\001" +
    "\002\000\004\014\175\001\002\000\004\014\167\001\002" +
    "\000\026\012\uffbf\013\uffbf\032\uffbf\033\uffbf\034\uffbf\035" +
    "\uffbf\040\uffbf\041\uffbf\042\uffbf\045\uffbf\001\002\000\016" +
    "\005\123\010\121\014\122\023\uffb8\024\uffb8\045\047\001" +
    "\002\000\026\012\uffc0\013\uffc0\032\uffc0\033\uffc0\034\uffc0" +
    "\035\uffc0\040\uffc0\041\uffc0\042\uffc0\045\uffc0\001\002\000" +
    "\004\045\047\001\002\000\004\014\161\001\002\000\026" +
    "\012\uffc3\013\uffc3\032\uffc3\033\uffc3\034\uffc3\035\uffc3\040" +
    "\uffc3\041\uffc3\042\uffc3\045\uffc3\001\002\000\024\012\065" +
    "\013\120\032\102\033\104\034\073\035\112\040\070\041" +
    "\105\045\117\001\002\000\026\012\uffc6\013\uffc6\032\uffc6" +
    "\033\uffc6\034\uffc6\035\uffc6\040\uffc6\041\uffc6\042\uffc6\045" +
    "\uffc6\001\002\000\024\012\uffc8\013\uffc8\032\uffc8\033\uffc8" +
    "\034\uffc8\035\uffc8\040\uffc8\041\uffc8\045\uffc8\001\002\000" +
    "\014\005\123\010\121\014\122\023\uffb8\024\uffb8\001\002" +
    "\000\006\031\uffe7\044\uffe7\001\002\000\012\014\125\021" +
    "\134\045\135\046\130\001\002\000\014\014\125\015\127" +
    "\021\134\045\135\046\130\001\002\000\004\016\124\001" +
    "\002\000\026\012\uffba\013\uffba\032\uffba\033\uffba\034\uffba" +
    "\035\uffba\040\uffba\041\uffba\042\uffba\045\uffba\001\002\000" +
    "\012\014\125\021\134\045\135\046\130\001\002\000\026" +
    "\004\uffd1\005\uffd1\006\uffd1\007\uffd1\011\uffd1\015\uffd1\016" +
    "\uffd1\017\uffd1\022\uffd1\025\uffd1\001\002\000\026\004\uffcd" +
    "\005\uffcd\006\uffcd\007\uffcd\011\uffcd\015\uffcd\016\uffcd\017" +
    "\uffcd\022\uffcd\025\uffcd\001\002\000\026\004\uffdb\005\uffdb" +
    "\006\uffdb\007\uffdb\011\uffdb\015\uffdb\016\uffdb\017\uffdb\022" +
    "\uffdb\025\uffdb\001\002\000\022\004\140\005\144\006\137" +
    "\007\143\015\uffcc\017\153\022\142\025\141\001\002\000" +
    "\026\004\uffd0\005\uffd0\006\uffd0\007\uffd0\011\uffd0\015\uffd0" +
    "\016\uffd0\017\uffd0\022\uffd0\025\uffd0\001\002\000\004\015" +
    "\152\001\002\000\012\014\125\021\134\045\135\046\130" +
    "\001\002\000\032\004\uffda\005\uffda\006\uffda\007\uffda\010" +
    "\121\011\uffda\014\122\015\uffda\016\uffda\017\uffda\022\uffda" +
    "\025\uffda\001\002\000\026\004\140\005\uffd5\006\137\007" +
    "\143\011\uffd5\015\uffd5\016\uffd5\017\uffd5\022\142\025\141" +
    "\001\002\000\012\014\125\021\134\045\135\046\130\001" +
    "\002\000\012\014\125\021\134\045\135\046\130\001\002" +
    "\000\012\014\125\021\134\045\135\046\130\001\002\000" +
    "\012\014\125\021\134\045\135\046\130\001\002\000\012" +
    "\014\125\021\134\045\135\046\130\001\002\000\026\004" +
    "\uffd6\005\uffd6\006\uffd6\007\uffd6\011\uffd6\015\uffd6\016\uffd6" +
    "\017\uffd6\022\uffd6\025\uffd6\001\002\000\026\004\uffd2\005" +
    "\uffd2\006\uffd2\007\uffd2\011\uffd2\015\uffd2\016\uffd2\017\uffd2" +
    "\022\uffd2\025\uffd2\001\002\000\026\004\uffd3\005\uffd3\006" +
    "\uffd3\007\143\011\uffd3\015\uffd3\016\uffd3\017\uffd3\022\uffd3" +
    "\025\uffd3\001\002\000\026\004\uffd4\005\uffd4\006\uffd4\007" +
    "\143\011\uffd4\015\uffd4\016\uffd4\017\uffd4\022\142\025\uffd4" +
    "\001\002\000\026\004\uffd8\005\uffd8\006\uffd8\007\143\011" +
    "\uffd8\015\uffd8\016\uffd8\017\uffd8\022\142\025\141\001\002" +
    "\000\026\004\140\005\uffd7\006\uffd7\007\143\011\uffd7\015" +
    "\uffd7\016\uffd7\017\uffd7\022\142\025\141\001\002\000\026" +
    "\004\uffce\005\uffce\006\uffce\007\uffce\011\uffce\015\uffce\016" +
    "\uffce\017\uffce\022\uffce\025\uffce\001\002\000\012\014\125" +
    "\021\134\045\135\046\130\001\002\000\004\015\uffcb\001" +
    "\002\000\020\004\140\005\144\006\137\007\143\015\156" +
    "\022\142\025\141\001\002\000\026\004\uffd9\005\uffd9\006" +
    "\uffd9\007\uffd9\011\uffd9\015\uffd9\016\uffd9\017\uffd9\022\uffd9" +
    "\025\uffd9\001\002\000\020\004\140\005\144\006\137\007" +
    "\143\011\160\022\142\025\141\001\002\000\032\004\uffcf" +
    "\005\uffcf\006\uffcf\007\uffcf\011\uffcf\015\uffcf\016\uffcf\017" +
    "\uffcf\022\uffcf\023\uffcf\024\uffcf\025\uffcf\001\002\000\012" +
    "\014\125\021\134\045\135\046\130\001\002\000\020\004" +
    "\140\005\144\006\137\007\143\015\163\022\142\025\141" +
    "\001\002\000\022\012\065\032\102\033\104\034\073\035" +
    "\112\040\070\041\105\045\117\001\002\000\026\012\uffad" +
    "\013\uffad\032\uffad\033\uffad\034\uffad\035\uffad\040\uffad\041" +
    "\uffad\042\uffad\045\uffad\001\002\000\004\016\166\001\002" +
    "\000\026\012\uffee\031\uffee\032\uffee\033\uffee\034\uffee\035" +
    "\uffee\040\uffee\041\uffee\044\uffee\045\uffee\001\002\000\012" +
    "\014\125\021\134\045\135\046\130\001\002\000\020\004" +
    "\140\005\144\006\137\007\143\015\171\022\142\025\141" +
    "\001\002\000\022\012\065\032\102\033\104\034\073\035" +
    "\112\040\070\041\105\045\117\001\002\000\026\012\uffb4" +
    "\013\uffb4\032\uffb4\033\uffb4\034\uffb4\035\uffb4\040\uffb4\041" +
    "\uffb4\042\173\045\uffb4\001\002\000\022\012\065\032\102" +
    "\033\104\034\073\035\112\040\070\041\105\045\117\001" +
    "\002\000\026\012\uffb5\013\uffb5\032\uffb5\033\uffb5\034\uffb5" +
    "\035\uffb5\040\uffb5\041\uffb5\042\uffb5\045\uffb5\001\002\000" +
    "\014\014\125\015\ufff8\021\134\045\135\046\130\001\002" +
    "\000\004\015\201\001\002\000\020\004\140\005\144\006" +
    "\137\007\143\015\uffa6\022\142\025\141\001\002\000\004" +
    "\015\uffa7\001\002\000\004\016\202\001\002\000\026\012" +
    "\uffaa\013\uffaa\032\uffaa\033\uffaa\034\uffaa\035\uffaa\040\uffaa" +
    "\041\uffaa\042\uffaa\045\uffaa\001\002\000\006\015\ufff8\047" +
    "\205\001\002\000\004\015\207\001\002\000\004\015\uffa8" +
    "\001\002\000\004\015\uffa9\001\002\000\004\016\210\001" +
    "\002\000\026\012\uffab\013\uffab\032\uffab\033\uffab\034\uffab" +
    "\035\uffab\040\uffab\041\uffab\042\uffab\045\uffab\001\002\000" +
    "\012\014\125\021\134\045\135\046\130\001\002\000\012" +
    "\014\125\021\134\045\135\046\130\001\002\000\020\004" +
    "\140\005\144\006\137\007\143\016\214\022\142\025\141" +
    "\001\002\000\026\012\uffb9\013\uffb9\032\uffb9\033\uffb9\034" +
    "\uffb9\035\uffb9\040\uffb9\041\uffb9\042\uffb9\045\uffb9\001\002" +
    "\000\020\004\140\005\144\006\137\007\143\016\216\022" +
    "\142\025\141\001\002\000\026\012\uffb6\013\uffb6\032\uffb6" +
    "\033\uffb6\034\uffb6\035\uffb6\040\uffb6\041\uffb6\042\uffb6\045" +
    "\uffb6\001\002\000\026\012\uffac\013\uffac\032\uffac\033\uffac" +
    "\034\uffac\035\uffac\040\uffac\041\uffac\042\uffac\045\uffac\001" +
    "\002\000\012\014\125\021\134\045\135\046\130\001\002" +
    "\000\020\004\140\005\144\006\137\007\143\015\222\022" +
    "\142\025\141\001\002\000\004\012\223\001\002\000\004" +
    "\026\226\001\002\000\010\013\ufff8\026\226\036\235\001" +
    "\002\000\010\013\uffb1\026\uffb1\036\uffb1\001\002\000\004" +
    "\046\227\001\002\000\004\020\230\001\002\000\004\012" +
    "\065\001\002\000\004\030\232\001\002\000\004\016\233" +
    "\001\002\000\010\013\uffb0\026\uffb0\036\uffb0\001\002\000" +
    "\004\013\244\001\002\000\004\020\240\001\002\000\010" +
    "\013\uffb2\026\uffb2\036\uffb2\001\002\000\004\013\uffae\001" +
    "\002\000\004\012\065\001\002\000\004\030\242\001\002" +
    "\000\004\016\243\001\002\000\004\013\uffaf\001\002\000" +
    "\026\012\uffb3\013\uffb3\032\uffb3\033\uffb3\034\uffb3\035\uffb3" +
    "\040\uffb3\041\uffb3\042\uffb3\045\uffb3\001\002\000\026\012" +
    "\ufff1\031\ufff1\032\ufff1\033\ufff1\034\ufff1\035\ufff1\040\ufff1" +
    "\041\ufff1\044\ufff1\045\ufff1\001\002\000\024\012\065\013" +
    "\247\032\102\033\104\034\073\035\112\040\070\041\105" +
    "\045\117\001\002\000\006\031\uffe5\044\uffe5\001\002\000" +
    "\026\012\uffbc\013\uffbc\032\uffbc\033\uffbc\034\uffbc\035\uffbc" +
    "\040\uffbc\041\uffbc\042\uffbc\045\uffbc\001\002\000\020\004" +
    "\140\005\144\006\137\007\143\016\252\022\142\025\141" +
    "\001\002\000\026\012\uffbb\013\uffbb\032\uffbb\033\uffbb\034" +
    "\uffbb\035\uffbb\040\uffbb\041\uffbb\042\uffbb\045\uffbb\001\002" +
    "\000\024\012\065\031\111\032\102\033\104\034\073\035" +
    "\112\040\070\041\105\045\107\001\002\000\024\012\065" +
    "\013\255\032\102\033\104\034\073\035\112\040\070\041" +
    "\105\045\117\001\002\000\030\012\uffc9\013\uffc9\030\uffc9" +
    "\032\uffc9\033\uffc9\034\uffc9\035\uffc9\040\uffc9\041\uffc9\042" +
    "\uffc9\045\uffc9\001\002\000\024\012\065\013\257\032\102" +
    "\033\104\034\073\035\112\040\070\041\105\045\117\001" +
    "\002\000\030\012\uffca\013\uffca\030\uffca\032\uffca\033\uffca" +
    "\034\uffca\035\uffca\040\uffca\041\uffca\042\uffca\045\uffca\001" +
    "\002\000\006\031\060\045\053\001\002\000\004\015\uffe0" +
    "\001\002\000\006\015\uffde\017\uffde\001\002\000\026\012" +
    "\uffef\031\uffef\032\uffef\033\uffef\034\uffef\035\uffef\040\uffef" +
    "\041\uffef\044\uffef\045\uffef\001\002\000\004\014\277\001" +
    "\002\000\004\014\266\001\002\000\004\015\267\001\002" +
    "\000\004\012\270\001\002\000\026\012\ufff8\031\ufff8\032" +
    "\ufff8\033\ufff8\034\ufff8\035\ufff8\040\ufff8\041\ufff8\043\017" +
    "\045\ufff8\001\002\000\024\012\065\031\111\032\102\033" +
    "\104\034\073\035\112\040\070\041\105\045\107\001\002" +
    "\000\024\012\065\031\111\032\102\033\104\034\073\035" +
    "\112\040\070\041\105\045\107\001\002\000\024\012\065" +
    "\013\274\032\102\033\104\034\073\035\112\040\070\041" +
    "\105\045\117\001\002\000\004\002\uffdd\001\002\000\024" +
    "\012\065\013\276\032\102\033\104\034\073\035\112\040" +
    "\070\041\105\045\117\001\002\000\004\002\uffdc\001\002" +
    "\000\010\015\ufff8\031\060\045\053\001\002\000\004\015" +
    "\301\001\002\000\004\012\302\001\002\000\026\012\ufff8" +
    "\031\ufff8\032\ufff8\033\ufff8\034\ufff8\035\ufff8\040\ufff8\041" +
    "\ufff8\043\017\045\ufff8\001\002\000\024\012\065\031\111" +
    "\032\102\033\104\034\073\035\112\040\070\041\105\045" +
    "\107\001\002\000\024\012\065\031\111\032\102\033\104" +
    "\034\073\035\112\040\070\041\105\045\107\001\002\000" +
    "\024\012\065\013\306\032\102\033\104\034\073\035\112" +
    "\040\070\041\105\045\117\001\002\000\006\031\uffe6\044" +
    "\uffe6\001\002\000\024\012\065\013\310\032\102\033\104" +
    "\034\073\035\112\040\070\041\105\045\117\001\002\000" +
    "\006\031\uffe4\044\uffe4\001\002\000\004\002\ufffc\001\002" +
    "\000\004\002\uffe9\001\002\000\004\045\314\001\002\000" +
    "\004\014\052\001\002\000\012\031\ufffa\043\ufffa\044\ufffa" +
    "\045\ufffa\001\002\000\004\046\317\001\002\000\004\016" +
    "\320\001\002\000\014\027\ufff7\031\ufff7\043\ufff7\044\ufff7" +
    "\045\ufff7\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\317\000\006\002\003\053\004\001\001\000\002\001" +
    "\001\000\006\003\005\054\006\001\001\000\002\001\001" +
    "\000\012\004\007\006\013\014\012\015\011\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\006\013\014\314" +
    "\015\011\001\001\000\010\006\017\016\014\017\015\001" +
    "\001\000\002\001\001\000\014\005\033\007\035\010\034" +
    "\021\036\022\031\001\001\000\010\006\017\016\030\017" +
    "\015\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\020\025\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\023\164\024\043\001\001\000\002\001\001" +
    "\000\010\005\033\007\311\010\034\001\001\000\002\001" +
    "\001\000\012\005\033\007\310\010\034\022\244\001\001" +
    "\000\002\001\001\000\006\023\041\024\043\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\023\045\024\043\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\006\056" +
    "\011\054\012\055\013\053\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\006\017\016\063\017\015\001\001\000\044" +
    "\021\070\022\031\026\071\027\074\030\076\031\113\032" +
    "\100\033\077\034\073\035\075\036\112\037\066\040\065" +
    "\044\107\045\105\047\102\052\114\001\001\000\044\021" +
    "\252\022\031\026\071\027\074\030\076\031\253\032\100" +
    "\033\077\034\073\035\075\036\112\037\066\040\065\044" +
    "\107\045\105\047\102\052\114\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\025\250\026\125\027\131\001" +
    "\001\000\042\022\244\026\071\027\074\030\076\031\245" +
    "\032\100\033\077\034\073\035\075\036\112\037\066\040" +
    "\065\044\107\045\105\047\102\052\114\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\023\164\024\043\001\001\000\002\001\001\000\006\023" +
    "\041\024\043\001\001\000\002\001\001\000\002\001\001" +
    "\000\036\026\071\027\074\030\076\032\115\033\077\034" +
    "\073\035\075\036\112\037\066\040\065\044\107\045\105" +
    "\047\102\052\114\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\025\156" +
    "\026\125\027\131\001\001\000\012\025\130\026\125\027" +
    "\131\046\132\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\025\154\026\125\027\131\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\025\135\026" +
    "\125\027\131\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\025\150\026\125\027\131\001\001\000\010\025" +
    "\147\026\125\027\131\001\001\000\010\025\146\026\125" +
    "\027\131\001\001\000\010\025\145\026\125\027\131\001" +
    "\001\000\010\025\144\026\125\027\131\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\025\130\026\125\027\131\046\153\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\025\161\026\125\027" +
    "\131\001\001\000\002\001\001\000\036\026\071\027\074" +
    "\030\076\032\163\033\077\034\073\035\075\036\112\037" +
    "\066\040\065\044\107\045\105\047\102\052\114\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\025\167\026\125\027\131\001\001\000\002\001\001" +
    "\000\036\026\071\027\074\030\076\032\171\033\077\034" +
    "\073\035\075\036\112\037\066\040\065\044\107\045\105" +
    "\047\102\052\114\001\001\000\002\001\001\000\036\026" +
    "\071\027\074\030\076\032\173\033\077\034\073\035\075" +
    "\036\112\037\066\040\065\044\107\045\105\047\102\052" +
    "\114\001\001\000\002\001\001\000\014\006\177\025\176" +
    "\026\125\027\131\051\175\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\006\205\050\203\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\025\214\026\125\027\131\001" +
    "\001\000\010\025\212\026\125\027\131\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\025\220\026\125\027\131" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\041" +
    "\223\042\224\001\001\000\010\006\236\042\235\043\233" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\030\230\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\030\240" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\036\026\071" +
    "\027\074\030\076\032\115\033\077\034\073\035\075\036" +
    "\112\037\066\040\065\044\107\045\105\047\102\052\114" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\042\022\244\026\071\027\074" +
    "\030\076\031\255\032\100\033\077\034\073\035\075\036" +
    "\112\037\066\040\065\044\107\045\105\047\102\052\114" +
    "\001\001\000\036\026\071\027\074\030\076\032\115\033" +
    "\077\034\073\035\075\036\112\037\066\040\065\044\107" +
    "\045\105\047\102\052\114\001\001\000\002\001\001\000" +
    "\036\026\071\027\074\030\076\032\115\033\077\034\073" +
    "\035\075\036\112\037\066\040\065\044\107\045\105\047" +
    "\102\052\114\001\001\000\002\001\001\000\006\012\260" +
    "\013\053\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\006\017\016\270\017" +
    "\015\001\001\000\044\021\271\022\031\026\071\027\074" +
    "\030\076\031\272\032\100\033\077\034\073\035\075\036" +
    "\112\037\066\040\065\044\107\045\105\047\102\052\114" +
    "\001\001\000\042\022\244\026\071\027\074\030\076\031" +
    "\274\032\100\033\077\034\073\035\075\036\112\037\066" +
    "\040\065\044\107\045\105\047\102\052\114\001\001\000" +
    "\036\026\071\027\074\030\076\032\115\033\077\034\073" +
    "\035\075\036\112\037\066\040\065\044\107\045\105\047" +
    "\102\052\114\001\001\000\002\001\001\000\036\026\071" +
    "\027\074\030\076\032\115\033\077\034\073\035\075\036" +
    "\112\037\066\040\065\044\107\045\105\047\102\052\114" +
    "\001\001\000\002\001\001\000\012\006\056\011\277\012" +
    "\055\013\053\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\006\017\016\302\017\015\001\001\000\044\021" +
    "\303\022\031\026\071\027\074\030\076\031\304\032\100" +
    "\033\077\034\073\035\075\036\112\037\066\040\065\044" +
    "\107\045\105\047\102\052\114\001\001\000\042\022\244" +
    "\026\071\027\074\030\076\031\306\032\100\033\077\034" +
    "\073\035\075\036\112\037\066\040\065\044\107\045\105" +
    "\047\102\052\114\001\001\000\036\026\071\027\074\030" +
    "\076\032\115\033\077\034\073\035\075\036\112\037\066" +
    "\040\065\044\107\045\105\047\102\052\114\001\001\000" +
    "\002\001\001\000\036\026\071\027\074\030\076\032\115" +
    "\033\077\034\073\035\075\036\112\037\066\040\065\044" +
    "\107\045\105\047\102\052\114\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	SyntaxErrorManager syntaxErrorManager = CompilerContext.getSyntaxErrorManager();
	
	public void syntax_error(Symbol symbol)
	{ 
	    Token token = (Token) symbol.value;
	    syntaxErrorManager.syntaxError ("Error sintactico", token);	    
	}
		
	public void unrecovered_syntax_error(java_cup.runtime.Symbol symbol)
	{	
	    Token token = (Token) symbol.value;
	    syntaxErrorManager.syntaxFatalError ("Error fatal", token);
	}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {


	
	SyntaxErrorManager   syntaxErrorManager   = CompilerContext.getSyntaxErrorManager();
	SemanticErrorManager semanticErrorManager = CompilerContext.getSemanticErrorManager ();
	ScopeManagerIF       scopeManager         = CompilerContext.getScopeManager ();
	FinalCodeFactoryIF   finalCodeFactory     = CompilerContext.getFinalCodeFactory ();


  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // opcionesEscribeEnt ::= expresion 
            {
              OpcionesEscribeEnt RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionesEscribeEnt",39, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // opcionesEscribeEnt ::= epsilon 
            {
              OpcionesEscribeEnt RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionesEscribeEnt",39, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // opcionesEscribe ::= STRING 
            {
              OpcionesEscribe RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionesEscribe",38, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // opcionesEscribe ::= epsilon 
            {
              OpcionesEscribe RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("opcionesEscribe",38, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // sentenciaSalida ::= ESCRIBE_ENT OPEN_KEY opcionesEscribeEnt CLOSE_KEY SEMI_COLON 
            {
              SentenciaSalida RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaSalida",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // sentenciaSalida ::= ESCRIBE OPEN_KEY opcionesEscribe CLOSE_KEY SEMI_COLON 
            {
              SentenciaSalida RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaSalida",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // sentenciaLlamadaFuncion ::= llamadaFuncion SEMI_COLON 
            {
              SentenciaLlamadaFuncion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaLlamadaFuncion",35, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // sentenciaMientras ::= MIENTRAS OPEN_KEY expresion CLOSE_KEY sentencia 
            {
              SentenciaMientras RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaMientras",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // porDefecto ::= epsilon 
            {
              PorDefecto RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("porDefecto",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // porDefecto ::= PORDEFECTO TWO_POINTS bloque CORTE SEMI_COLON 
            {
              PorDefecto RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("porDefecto",33, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // casoAlt ::= CASO NUMERO TWO_POINTS bloque CORTE SEMI_COLON 
            {
              CasoAlt RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("casoAlt",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // casosAlternativa ::= casoAlt 
            {
              CasosAlternativa RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("casosAlternativa",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // casosAlternativa ::= casosAlternativa casoAlt 
            {
              CasosAlternativa RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("casosAlternativa",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // sentenciaAlternativas ::= ALTENATIVAS OPEN_KEY expresion CLOSE_KEY OPEN_PARENTHESIS casosAlternativa porDefecto CLOSE_PARENTHESIS 
            {
              SentenciaAlternativas RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaAlternativas",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // sentenciaSi ::= SI OPEN_KEY expresion CLOSE_KEY sentencia 
            {
              SentenciaSi RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaSi",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // sentenciaSi ::= SI OPEN_KEY expresion CLOSE_KEY sentencia SINO sentencia 
            {
              SentenciaSi RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaSi",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // sentenciaAsignacionSuma ::= ref ASSIGN_SUMA expresion SEMI_COLON 
            {
              SentenciaAsignacionSuma RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaAsignacionSuma",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // ref ::= accesoVector 
            {
              Ref RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ref",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // ref ::= IDENTIFICADOR 
            {
              Ref RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ref",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // sentenciaAsignacion ::= ref ASSIGN expresion SEMI_COLON 
            {
              SentenciaAsignacion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaAsignacion",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // sentenciaIncremento ::= IDENTIFICADOR AUTO_INCREMENTO SEMI_COLON 
            {
              SentenciaIncremento RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaIncremento",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // sentenciaDevuelve ::= DEVUELVE expresion SEMI_COLON 
            {
              SentenciaDevuelve RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaDevuelve",40, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // sentenciaDevuelve ::= DEVUELVE SEMI_COLON 
            {
              SentenciaDevuelve RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaDevuelve",40, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // sentencia ::= bloque 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // sentencia ::= sentenciaSalida 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // sentencia ::= sentenciaLlamadaFuncion 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // sentencia ::= sentenciaMientras 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // sentencia ::= sentenciaAlternativas 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // sentencia ::= sentenciaSi 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // sentencia ::= sentenciaAsignacionSuma 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // sentencia ::= sentenciaAsignacion 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // sentencia ::= sentenciaIncremento 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // sentencia ::= sentenciaDevuelve 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // listadoSentencias ::= sentencia 
            {
              ListadoSentencias RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listadoSentencias",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // listadoSentencias ::= listadoSentencias sentencia 
            {
              ListadoSentencias RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listadoSentencias",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // bloque ::= OPEN_PARENTHESIS listadoSentencias CLOSE_PARENTHESIS 
            {
              Bloque RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloque",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // bloque ::= OPEN_PARENTHESIS seccionVariables listadoSentencias CLOSE_PARENTHESIS 
            {
              Bloque RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloque",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // parametros ::= expresion COLON parametros 
            {
              Parametros RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametros",36, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // parametros ::= expresion 
            {
              Parametros RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametros",36, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // llamadaFuncion ::= IDENTIFICADOR OPEN_KEY CLOSE_KEY 
            {
              LlamadaFuncion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("llamadaFuncion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // llamadaFuncion ::= IDENTIFICADOR OPEN_KEY parametros CLOSE_KEY 
            {
              LlamadaFuncion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("llamadaFuncion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // accesoVector ::= IDENTIFICADOR OPEN_BRACKET expresion CLOSE_BRACKET 
            {
              AccesoVector RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accesoVector",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expresion ::= llamadaFuncion 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expresion ::= accesoVector 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expresion ::= expresion AND_LOGICA expresion 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expresion ::= expresion EQUAL expresion 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expresion ::= expresion LOWER_THAN expresion 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // expresion ::= NEGACION expresion 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // expresion ::= expresion AUTO_INCREMENTO 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // expresion ::= expresion MULT expresion 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expresion ::= expresion PLUS expresion 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
			 		Expresion e = new Expresion(e1, e2);
			 		// comprobacion de tipos de e1 y e2
			 		// generacion de codigo de e1 + e2
			 		// ...
			 		RESULT = e;	
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expresion ::= OPEN_KEY expresion CLOSE_KEY 
            {
              Expresion RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
		        	Expresion e = new Expresion();  // generamos un objeto nuevo del tipo de la parte izq de la regla (en este caso, el antecedente es expresion y su clase Expresion)
		        	RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expresion ::= IDENTIFICADOR 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expresion ::= NUMERO 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // funcionPrincipal ::= VACIO principal OPEN_KEY CLOSE_KEY OPEN_PARENTHESIS seccionTipos seccionVariables listadoSentencias CLOSE_PARENTHESIS 
            {
              FuncionPrincipal RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("funcionPrincipal",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // funcionPrincipal ::= VACIO principal OPEN_KEY CLOSE_KEY OPEN_PARENTHESIS seccionTipos listadoSentencias CLOSE_PARENTHESIS 
            {
              FuncionPrincipal RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("funcionPrincipal",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // parametro ::= IDENTIFICADOR IDENTIFICADOR 
            {
              Parametro RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // parametro ::= ENTERO IDENTIFICADOR 
            {
              Parametro RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // declaracionParametros ::= parametro COLON declaracionParametros 
            {
              DeclaracionParametros RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionParametros",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // declaracionParametros ::= parametro 
            {
              DeclaracionParametros RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionParametros",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // seccionParametros ::= epsilon 
            {
              SeccionParametros RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionParametros",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // seccionParametros ::= declaracionParametros 
            {
              SeccionParametros RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionParametros",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // funcion ::= VACIO IDENTIFICADOR OPEN_KEY seccionParametros CLOSE_KEY OPEN_PARENTHESIS seccionTipos seccionVariables listadoSentencias CLOSE_PARENTHESIS 
            {
              Funcion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("funcion",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // funcion ::= ENTERO IDENTIFICADOR OPEN_KEY seccionParametros CLOSE_KEY OPEN_PARENTHESIS seccionTipos seccionVariables listadoSentencias CLOSE_PARENTHESIS 
            {
              Funcion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("funcion",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // funcion ::= VACIO IDENTIFICADOR OPEN_KEY seccionParametros CLOSE_KEY OPEN_PARENTHESIS seccionTipos listadoSentencias CLOSE_PARENTHESIS 
            {
              Funcion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("funcion",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // funcion ::= ENTERO IDENTIFICADOR OPEN_KEY seccionParametros CLOSE_KEY OPEN_PARENTHESIS seccionTipos listadoSentencias CLOSE_PARENTHESIS 
            {
              Funcion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("funcion",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // seccionFunciones ::= funcionPrincipal 
            {
              SeccionFunciones RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionFunciones",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // seccionFunciones ::= funcion seccionFunciones 
            {
              SeccionFunciones RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionFunciones",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // id ::= IDENTIFICADOR ASSIGN NUMERO 
            {
              Id RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("id",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // id ::= IDENTIFICADOR 
            {
              Id RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("id",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // listadoIDs ::= id 
            {
              ListadoIDs RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listadoIDs",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // listadoIDs ::= id COLON listadoIDs 
            {
              ListadoIDs RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listadoIDs",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // declaracionVariable ::= IDENTIFICADOR listadoIDs SEMI_COLON 
            {
              DeclaracionVariable RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariable",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // declaracionVariable ::= ENTERO listadoIDs SEMI_COLON 
            {
              DeclaracionVariable RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariable",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // seccionVariables ::= declaracionVariable 
            {
              SeccionVariables RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionVariables",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // seccionVariables ::= seccionVariables declaracionVariable 
            {
              SeccionVariables RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionVariables",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // tamTipo ::= IDENTIFICADOR 
            {
              TamTipo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tamTipo",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // tamTipo ::= NUMERO 
            {
              TamTipo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tamTipo",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // declaracionTipo ::= TIPO ENTERO IDENTIFICADOR OPEN_BRACKET tamTipo CLOSE_BRACKET SEMI_COLON 
            {
              DeclaracionTipo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionTipo",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // seccionTipos ::= epsilon 
            {
              SeccionTipos RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionTipos",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // seccionTipos ::= declaracionTipo seccionTipos 
            {
              SeccionTipos RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionTipos",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // declaracionConstante ::= CONSTANTE IDENTIFICADOR NUMERO SEMI_COLON 
            {
              DeclaracionConstante RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Token value = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
							
							// Obtenemos el ambito donde nos encontramos y obtenemos la tabla de simbolos 
							ScopeIF scope = scopeManager.getCurrentScope();
							SymbolTableIF tablaSimbolos = scope.getSymbolTable();
							String name = id.getLexema();
							
							// Comprobamos que la constante no este ya declarada en la tabla de simbolos
							if(tablaSimbolos.containsSymbol(name)){
								semanticErrorManager.semanticFatalError("Constante " + name + " ya declarada");								
							}else{
								System.out.println("Constante " + name + " aun NO declarada");
														
								// Introducimos en la tabla de simbolos la constante con su ambito, nombre, tipo y valor
								TypeTableIF tablaTipos = scope.getTypeTable();
								TypeIF tipo = scopeManager.searchType("ENTERO");  // en la pec de referencia las constantes eran todas enteras
								SymbolConstant symbolConstant = new SymbolConstant(scope, name, tipo);
								symbolConstant.setValue(value.getLexema()); // para esto se ha modificado la clase SymbolConstant en semantic.symbol
								tablaSimbolos.addSymbol(symbolConstant);								
							}
					   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionConstante",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // epsilon ::= 
            {
              Epsilon RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("epsilon",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // seccionConstantes ::= epsilon 
            {
              SeccionConstantes RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionConstantes",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // seccionConstantes ::= declaracionConstante seccionConstantes 
            {
              SeccionConstantes RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionConstantes",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // axiom ::= seccionConstantes seccionTipos seccionFunciones 
            {
              Axiom RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // axiom ::= seccionConstantes seccionTipos seccionVariables seccionFunciones 
            {
              Axiom RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // initAxiom ::= NT$1 axiom 
            {
              Axiom RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Axiom) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
					
				//cerramos ambito global	
				scopeManager.closeScope();				
		    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("initAxiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // NT$1 ::= 
            {
              Axiom RESULT =null;

				// Creamos ambito global 
				String idLexema  = "global";								
				ScopeIF scope = scopeManager.openScope(idLexema);
				
				// Comprobamos que se ha creado correctamente y su nivel es 0
				System.out.println("El nombre del nuevo �mbito es " + scope.getName());
				System.out.println("El nivel del nuevo �mbito es " + scope.getLevel());
				
				// Obtenemos la tabla de tipos y la de simbolos del ambito global
				SymbolTableIF symbolTable = scope.getSymbolTable();
				TypeTableIF typeTable = scope.getTypeTable();
				
				// Introduccion en la tabla de tipos del tipo simple entero
				
				// Introduccion en la tabla de tipos del tipo simple vacio
			
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",42, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= NT$0 initAxiom 
            {
              Program RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Program) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int axleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int axright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Axiom ax = (Axiom)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		   		
  		// No modificar esta estructura, aunque se pueden añadir más acciones semánticas
  		
  		//List intermediateCode = ax.getIntermediateCode ();
  		//finalCodeFactory.create (intermediateCode);

  		// En caso de no comentarse las dos sentencias anteriores se puede generar una excepcion
  		// en las llamadas a cupTest si el compilador no está completo. Esto es debido a que 
  		// aún no se tendrá implementada la generación de código intermedio ni final.
  		// Para la entrega final deberán descomentarse y usarse.
  		
  		syntaxErrorManager.syntaxInfo ("Parsing process ended.");
  		
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // NT$0 ::= 
            {
              Program RESULT =null;
 
        syntaxErrorManager.syntaxInfo ("Starting parsing..."); 
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",41, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Program start_val = (Program)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

